// Central sharing/export module for JDCA.
//
// Produces REAL files (not screenshots):
//   • Scorecard, Teams roster, and Points table as designed PDFs (jsPDF + autotable)
//   • Match result as a branded PNG card for WhatsApp / Instagram (Canvas 2D)
//
// jsPDF is lazy-loaded so it never enters the initial bundle — it only loads
// the first time a user taps Share/Download. Everything works offline once the
// chunk + logo are cached by the service worker.

// ── Brand palette (JDCA v3) ─────────────────────────────────────────────
export const BRAND = {
  navy: '#0B1628',
  blue: '#1D4ED8',
  bg: '#F0F4F8',
  ink: '#1E293B',
  grey: '#64748B',
  line: '#E2E8F0',
  white: '#FFFFFF',
  green: '#15803D',
  red: '#DC2626',
  amber: '#B45309',
};

const hexToRgb = (h) => {
  const n = parseInt(h.replace('#', ''), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
};

// ── Logo cache (fetched from same origin, SW-cached) ────────────────────
let _logoPromise = null;
function loadLogoDataUrl() {
  if (_logoPromise) return _logoPromise;
  _logoPromise = (async () => {
    try {
      const res = await fetch('/jdca-logo.png');
      if (!res.ok) return null;
      const blob = await res.blob();
      return await new Promise((resolve) => {
        const r = new FileReader();
        r.onloadend = () => resolve(r.result);
        r.onerror = () => resolve(null);
        r.readAsDataURL(blob);
      });
    } catch {
      return null;
    }
  })();
  return _logoPromise;
}

let _jspdfPromise = null;
async function loadJsPDF() {
  if (!_jspdfPromise) {
    _jspdfPromise = (async () => {
      const [{ jsPDF }, autoTableMod] = await Promise.all([
        import('jspdf'),
        import('jspdf-autotable'),
      ]);
      const autoTable = autoTableMod.default || autoTableMod.autoTable;
      return { jsPDF, autoTable };
    })();
  }
  return _jspdfPromise;
}

// ── Universal "share a file, else download it" ──────────────────────────
// Uses the Web Share API with files where supported (mobile), otherwise
// falls back to a normal download. Never throws on a user cancel.
export async function shareOrDownload(blob, filename, { title, text, forceDownload } = {}) {
  const file = new File([blob], filename, { type: blob.type });
  try {
    if (!forceDownload && navigator.canShare && navigator.canShare({ files: [file] })) {
      await navigator.share({ files: [file], title, text });
      return 'shared';
    }
  } catch (err) {
    // AbortError = user dismissed the sheet. Treat as handled, don't fall back.
    if (err && err.name === 'AbortError') return 'cancelled';
  }
  // Fallback: trigger a download
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
  return 'downloaded';
}

const slug = (s) => String(s || 'jdca').replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '').toLowerCase();

// ── Shared PDF chrome (header band + footer) ────────────────────────────
async function paintHeader(doc, { title, subtitle }) {
  const W = doc.internal.pageSize.getWidth();
  doc.setFillColor(...hexToRgb(BRAND.navy));
  doc.rect(0, 0, W, 86, 'F');

  const logo = await loadLogoDataUrl();
  if (logo) {
    try { doc.addImage(logo, 'PNG', 40, 20, 46, 46); } catch { /* ignore */ }
  }
  const x = logo ? 100 : 40;
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('JABALPUR DIVISION CRICKET ASSOCIATION', x, 32);
  doc.setFontSize(17);
  doc.text(title, x, 54);
  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(176, 190, 210);
    doc.text(subtitle, x, 71);
  }
}

function paintFooter(doc) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...hexToRgb(BRAND.line));
    doc.setLineWidth(0.7);
    doc.line(40, H - 34, W - 40, H - 34);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...hexToRgb(BRAND.grey));
    doc.text('Generated by the official JDCA Scoring App', 40, H - 20);
    doc.text(`Page ${i} of ${pages}`, W - 40, H - 20, { align: 'right' });
    const stamp = new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });
    doc.text(stamp, W / 2, H - 20, { align: 'center' });
  }
}

function sectionTitle(doc, text, y) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...hexToRgb(BRAND.navy));
  doc.text(text, 40, y);
  return y + 6;
}

const tableTheme = (headColor = BRAND.navy) => ({
  theme: 'grid',
  margin: { left: 40, right: 40 },
  styles: { font: 'helvetica', fontSize: 8.5, cellPadding: 5, textColor: hexToRgb(BRAND.ink), lineColor: hexToRgb(BRAND.line), lineWidth: 0.5 },
  headStyles: { fillColor: hexToRgb(headColor), textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8.5, halign: 'left' },
  alternateRowStyles: { fillColor: hexToRgb(BRAND.bg) },
});

// ════════════════════════════════════════════════════════════════════════
// 1. SCORECARD PDF
// ════════════════════════════════════════════════════════════════════════
export async function shareScorecardPdf(scorecard = {}, match = {}, opts = {}) {
  const { jsPDF, autoTable } = await loadJsPDF();
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();

  const homeName = scorecard?.home_team?.name || match?.home_team?.name || 'Home Team';
  const awayName = scorecard?.away_team?.name || match?.away_team?.name || 'Away Team';
  const tournament = scorecard?.tournament || match?.tournament || 'JDCA Fixture';
  const venue = scorecard?.venue || match?.venue_name || match?.venue || '—';
  const matchDate = scorecard?.date || match?.date
    || (match?.scheduled_at ? new Date(match.scheduled_at).toLocaleDateString('en-IN', { dateStyle: 'medium' }) : '');
  const umpire = scorecard?.umpire || match?.umpire_name || match?.umpireName || '';
  const scorer = scorecard?.scorer || match?.scorer_name || match?.scorerName || '';

  await paintHeader(doc, { title: 'Match Scorecard', subtitle: `${tournament}  ·  ${venue}` });

  // Summary band
  let y = 108;
  doc.setFillColor(...hexToRgb(BRAND.bg));
  doc.roundedRect(40, y, W - 80, 58, 6, 6, 'F');
  const col = (W - 80) / 2;
  const drawTeamScore = (name, score, overs, x, align) => {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(...hexToRgb(BRAND.navy));
    doc.text(name, x, y + 24, { align });
    doc.setFontSize(16); doc.setTextColor(...hexToRgb(BRAND.blue));
    doc.text(score || '—', x, y + 46, { align });
    if (overs) {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(...hexToRgb(BRAND.grey));
      const sw = doc.getTextWidth(score || '—');
      doc.text(`  ${overs}`, align === 'right' ? x - sw - 4 : x + sw + 6, y + 46, { align: align === 'right' ? 'right' : 'left' });
    }
  };
  const cleanOvers = (o) => (o || '').replace('(', '').replace(' ov)', '').replace(')', '');
  drawTeamScore(homeName, scorecard?.home_team?.score, cleanOvers(scorecard?.home_team?.overs), 56, 'left');
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...hexToRgb(BRAND.grey));
  doc.text('VS', 40 + col + 0, y + 36, { align: 'center' });
  drawTeamScore(awayName, scorecard?.away_team?.score, cleanOvers(scorecard?.away_team?.overs), W - 56, 'right');
  y += 58 + 14;

  // Result banner
  const resultText = scorecard?.resultText || match?.result_text;
  if (resultText) {
    doc.setFillColor(...hexToRgb(BRAND.blue));
    doc.roundedRect(40, y, W - 80, 24, 5, 5, 'F');
    doc.setFont('helvetica', 'bold'); doc.setFontSize(9.5); doc.setTextColor(255, 255, 255);
    doc.text(resultText, W / 2, y + 16, { align: 'center' });
    y += 24 + 14;
  }

  const motm = resolveMotmName(scorecard, match);
  if (motm) {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...hexToRgb(BRAND.amber));
    doc.text(`Player of the Match: ${motm}`, 40, y);
    y += 16;
  }

  // Match details — tournament / venue / date / officials
  const detailRows = [
    ['Tournament', tournament],
    ['Venue', venue],
    matchDate ? ['Date', matchDate] : null,
    ['Umpire', umpire || '—'],
    ['Scorer', scorer || '—'],
  ].filter(Boolean);
  y = sectionTitle(doc, 'Match Details', y + 8) + 6;
  autoTable(doc, {
    ...tableTheme(),
    startY: y,
    head: [['Detail', 'Value']],
    body: detailRows.map(([k, v]) => [k, v || '—']),
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 150 } },
  });
  y = doc.lastAutoTable.finalY + 10;

  // Both innings — full scoresheet for each team (never a single-team toggle)
  const innings = [
    { label: `${homeName} — Innings`, data: scorecard?.scorecard?.home_team, bowlLabel: awayName },
    { label: `${awayName} — Innings`, data: scorecard?.scorecard?.away_team, bowlLabel: homeName },
  ];

  for (const inn of innings) {
    if (!inn.data || ((inn.data.batting || []).length === 0 && (inn.data.bowling || []).length === 0)) continue;
    if (y > doc.internal.pageSize.getHeight() - 200) { doc.addPage(); y = 60; }

    y = sectionTitle(doc, inn.label, y + 8) + 6;
    autoTable(doc, {
      ...tableTheme(),
      startY: y,
      head: [['Batter', 'Dismissal', 'R', 'B', '4s', '6s', 'SR']],
      body: (inn.data.batting || []).map((b) => [
        b.name || '—', b.dismissal || 'not out',
        n(b.runs), n(b.balls), n(b.fours), n(b.sixes), b.strikeRate ?? '0.0',
      ]),
      columnStyles: { 2: { halign: 'right', fontStyle: 'bold' }, 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' }, 6: { halign: 'right' } },
    });
    y = doc.lastAutoTable.finalY + 4;

    const extras = inn.data === scorecard?.scorecard?.home_team ? scorecard?.home_team?.extras : scorecard?.away_team?.extras;
    const totalScore = inn.data === scorecard?.scorecard?.home_team ? scorecard?.home_team?.score : scorecard?.away_team?.score;
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(...hexToRgb(BRAND.grey));
    doc.text(`Extras: ${n(extras)}`, 40, y + 11);
    doc.setFont('helvetica', 'bold'); doc.setTextColor(...hexToRgb(BRAND.navy));
    doc.text(`Total: ${totalScore || '0/0'}`, W - 40, y + 11, { align: 'right' });
    y += 22;

    autoTable(doc, {
      ...tableTheme(BRAND.blue),
      startY: y,
      head: [['Bowler', 'O', 'M', 'R', 'W', 'Econ', 'WD', 'NB']],
      body: (inn.data.bowling || []).map((bo) => [
        bo.name || '—', bo.overs ?? '0', n(bo.maidens), n(bo.runs), n(bo.wickets), bo.economy ?? '0.00', n(bo.wides), n(bo.noBalls),
      ]),
      columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right', fontStyle: 'bold' }, 5: { halign: 'right' }, 6: { halign: 'right' }, 7: { halign: 'right' } },
    });
    y = doc.lastAutoTable.finalY + 6;

    const fow = inn.data.fallOfWickets || [];
    if (fow.length) {
      const txt = 'Fall of wickets: ' + fow.map((f) => `${f.wicket}-${f.score} (${f.player}, ${f.oversAt} ov)`).join(', ');
      doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...hexToRgb(BRAND.grey));
      const lines = doc.splitTextToSize(txt, W - 80);
      doc.text(lines, 40, y + 8);
      y += 8 + lines.length * 10 + 6;
    }
  }

  paintFooter(doc);
  const fname = `scorecard-${slug(homeName)}-vs-${slug(awayName)}.pdf`;
  return shareOrDownload(doc.output('blob'), fname, {
    title: `${homeName} vs ${awayName} — Scorecard`,
    text: resultText || `${homeName} vs ${awayName}`,
    forceDownload: opts.forceDownload,
  });
}

// ════════════════════════════════════════════════════════════════════════
// 2. TEAM ROSTER PDF (single team)
// ════════════════════════════════════════════════════════════════════════
export async function shareTeamRosterPdf(team = {}, opts = {}) {
  const { jsPDF, autoTable } = await loadJsPDF();
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();

  await paintHeader(doc, { title: team.name || 'Team Sheet', subtitle: `${team.category || ''} ${team.gender || ''}  ·  ${team.district || ''}`.trim() });

  let y = 108;
  const meta = [
    ['Captain', team.captain || '—'],
    ['Vice-Captain', team.viceCaptain || '—'],
    ['Wicket-Keeper', team.wicketKeeper || '—'],
    ['Squad Size', String((team.squad || []).length)],
  ];
  autoTable(doc, {
    ...tableTheme(),
    startY: y,
    head: [['Team Detail', 'Value']],
    body: meta,
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 150 } },
  });
  y = doc.lastAutoTable.finalY + 14;

  y = sectionTitle(doc, 'Squad', y) + 6;
  autoTable(doc, {
    ...tableTheme(BRAND.blue),
    startY: y,
    head: [['#', 'Player', 'Role', 'District']],
    body: (team.squad || []).map((p, i) => [
      String(i + 1),
      p.full_name || p.name || '—',
      p.primary_role || p.role || '—',
      p.district || '—',
    ]),
    columnStyles: { 0: { cellWidth: 28, halign: 'right' } },
  });

  paintFooter(doc);
  return shareOrDownload(doc.output('blob'), `team-${slug(team.name)}.pdf`, {
    title: `${team.name} — Official Team Sheet`,
    forceDownload: opts.forceDownload,
  });
}

// ════════════════════════════════════════════════════════════════════════
// 3. TEAMS DIRECTORY PDF (list of teams)
// ════════════════════════════════════════════════════════════════════════
export async function shareTeamsListPdf(teams = [], { title = 'Official Teams Directory', subtitle = 'Season 2026', forceDownload } = {}) {
  const { jsPDF, autoTable } = await loadJsPDF();
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  await paintHeader(doc, { title, subtitle });
  autoTable(doc, {
    ...tableTheme(),
    startY: 108,
    head: [['Team', 'Category', 'Gender', 'District', 'Captain', 'Players']],
    body: (teams || []).map((t) => [
      t.name || '—', t.category || '—', t.gender || '—', t.district || '—', t.captain || '—', String((t.squad || []).length || t.activePlayers || 0),
    ]),
    columnStyles: { 5: { halign: 'right' } },
  });
  paintFooter(doc);
  return shareOrDownload(doc.output('blob'), 'jdca-teams-directory.pdf', { title, forceDownload });
}

// ════════════════════════════════════════════════════════════════════════
// 4. POINTS TABLE PDF
// ════════════════════════════════════════════════════════════════════════
export async function sharePointsTablePdf(rows = [], { title = 'Points Table', subtitle = 'Season 2026', forceDownload } = {}) {
  const { jsPDF, autoTable } = await loadJsPDF();
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  await paintHeader(doc, { title, subtitle });
  autoTable(doc, {
    ...tableTheme(),
    startY: 108,
    head: [['#', 'Team', 'P', 'W', 'L', 'T', 'NR', 'Pts', 'NRR', 'Form']],
    body: (rows || []).map((r, i) => [
      String(i + 1), r.team || '—', n(r.m), n(r.w), n(r.l), n(r.t), n(r.nr), n(r.pts), r.nrr ?? '0.000',
      (r.form || []).slice(-5).join(' '),
    ]),
    columnStyles: {
      0: { cellWidth: 24, halign: 'right' },
      2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' },
      6: { halign: 'right' }, 7: { halign: 'right', fontStyle: 'bold' }, 8: { halign: 'right' },
    },
    didParseCell: (hook) => {
      if (hook.section === 'body' && hook.column.index === 7) hook.cell.styles.textColor = hexToRgb(BRAND.blue);
    },
  });
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...hexToRgb(BRAND.grey));
  doc.text('P-Played  W-Won  L-Lost  T-Tied  NR-No Result  Pts-Points  NRR-Net Run Rate.  Win = 2 pts, Tie/No Result = 1 pt.',
    40, doc.lastAutoTable.finalY + 16);
  paintFooter(doc);
  return shareOrDownload(doc.output('blob'), 'jdca-points-table.pdf', { title, forceDownload });
}

// ════════════════════════════════════════════════════════════════════════
// 5. SOCIAL RESULT CARD (PNG via Canvas 2D) — for WhatsApp / Instagram
// ════════════════════════════════════════════════════════════════════════
export async function shareResultCardImage(match = {}, highlights = {}) {
  const S = 2; // retina scale
  const w = 1080, h = 1080; // square card for WhatsApp / Instagram
  const canvas = document.createElement('canvas');
  canvas.width = w * S; canvas.height = h * S;
  const ctx = canvas.getContext('2d');
  ctx.scale(S, S);

  const homeName = match?.home_team?.name || 'Home';
  const awayName = match?.away_team?.name || 'Away';
  const homeScore = match?.home_team?.score || '—';
  const awayScore = match?.away_team?.score || '—';
  const resultText = match?.resultText || match?.result_text || match?.result || 'Match Result';
  const tournament = match?.tournament || match?.stage || 'JDCA Fixture';
  const venue = match?.venue || '';

  // Background: navy gradient
  const g = ctx.createLinearGradient(0, 0, w, h);
  g.addColorStop(0, '#0B1628'); g.addColorStop(1, '#13233f');
  ctx.fillStyle = g; ctx.fillRect(0, 0, w, h);

  // Accent bar
  ctx.fillStyle = BRAND.blue; ctx.fillRect(0, 0, w, 14);

  const center = w / 2;
  const txt = (s, x, yy, { size = 40, weight = 'bold', color = '#fff', align = 'center', spacing } = {}) => {
    ctx.fillStyle = color;
    ctx.font = `${weight} ${size}px Helvetica, Arial, sans-serif`;
    ctx.textAlign = align; ctx.textBaseline = 'alphabetic';
    if (spacing) {
      // simple letter-spacing for the eyebrow label
      const chars = s.split(''); let cx = x - (measureSpaced(ctx, s, spacing) / 2);
      ctx.textAlign = 'left';
      for (const c of chars) { ctx.fillText(c, cx, yy); cx += ctx.measureText(c).width + spacing; }
      ctx.textAlign = align;
    } else {
      ctx.fillText(s, x, yy);
    }
  };

  // Logo
  const logo = await loadLogoDataUrl();
  if (logo) {
    try {
      const img = await loadImage(logo);
      ctx.drawImage(img, center - 70, 70, 140, 140);
    } catch { /* ignore */ }
  }

  txt('JABALPUR DIVISION CRICKET ASSOCIATION', center, 255, { size: 20, color: '#8FA6C8', spacing: 3 });
  txt(fit(ctx, tournament.toUpperCase(), 900, 26, 'bold'), center, 300, { size: 26, color: '#5B8DEF' });

  // Teams + scores
  txt(fit(ctx, homeName, 960, 52, 'bold'), center, 430, { size: 52, color: '#fff' });
  txt(homeScore, center, 500, { size: 62, color: '#9DBFF5', weight: 'bold' });

  txt('VS', center, 570, { size: 28, color: '#64748B' });

  txt(fit(ctx, awayName, 960, 52, 'bold'), center, 660, { size: 52, color: '#fff' });
  txt(awayScore, center, 730, { size: 62, color: '#9DBFF5', weight: 'bold' });

  // Result pill
  const rLines = wrapText(ctx, resultText, 900, 34, 'bold');
  const pillH = 40 + rLines.length * 44;
  const pillY = 790;
  roundRect(ctx, center - 460, pillY, 920, pillH, 18);
  ctx.fillStyle = BRAND.blue; ctx.fill();
  rLines.forEach((ln, i) => txt(ln, center, pillY + 54 + i * 44, { size: 34, color: '#fff' }));

  // Highlights
  let hy = pillY + pillH + 70;
  const tb = highlights?.topBatter, tbow = highlights?.topBowler;
  if (tb?.name) { txt('TOP BATTER', center - 230, hy, { size: 18, color: '#64748B', spacing: 2 }); txt(fit(ctx, tb.name, 420, 30, 'bold'), center - 230, hy + 38, { size: 30, color: '#fff' }); }
  if (tbow?.name) { txt('TOP BOWLER', center + 230, hy, { size: 18, color: '#64748B', spacing: 2 }); txt(fit(ctx, tbow.name, 420, 30, 'bold'), center + 230, hy + 38, { size: 30, color: '#fff' }); }

  if (venue) txt(fit(ctx, venue, 960, 22), center, h - 40, { size: 22, color: '#64748B', weight: 'normal' });

  const blob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/png', 0.95));
  if (!blob) throw new Error('Could not render result card');
  return shareOrDownload(blob, `result-${slug(homeName)}-vs-${slug(awayName)}.png`, {
    title: `${homeName} vs ${awayName}`,
    text: resultText,
  });
}

// ── tiny helpers ────────────────────────────────────────────────────────
const n = (v) => (v === 0 || v ? String(v) : '0');

function resolveMotmName(scorecard, match) {
  const cands = [scorecard?.manOfTheMatch, scorecard?.man_of_the_match, scorecard?.playerOfMatch, match?.man_of_the_match, match?.playerOfMatch];
  for (const c of cands) {
    if (!c) continue;
    const v = Array.isArray(c) ? c[0] : c;
    if (typeof v === 'string' && v.trim()) return v.trim();
    if (v?.full_name || v?.name) return v.full_name || v.name;
  }
  return null;
}

function loadImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}
function measureSpaced(ctx, s, spacing) {
  let total = 0;
  for (const c of s) total += ctx.measureText(c).width + spacing;
  return total - spacing;
}
function roundRect(ctx, x, y, w, h, r) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}
// shrink font until the text fits maxWidth; returns the (possibly unchanged) text
function fit(ctx, text, maxWidth, size, weight = 'bold') {
  ctx.font = `${weight} ${size}px Helvetica, Arial, sans-serif`;
  let t = String(text || '');
  if (ctx.measureText(t).width <= maxWidth) return t;
  while (t.length > 4 && ctx.measureText(t + '…').width > maxWidth) t = t.slice(0, -1);
  return t + '…';
}
function wrapText(ctx, text, maxWidth, size, weight = 'bold') {
  ctx.font = `${weight} ${size}px Helvetica, Arial, sans-serif`;
  const words = String(text || '').split(/\s+/);
  const lines = []; let line = '';
  for (const word of words) {
    const test = line ? line + ' ' + word : word;
    if (ctx.measureText(test).width > maxWidth && line) { lines.push(line); line = word; }
    else line = test;
  }
  if (line) lines.push(line);
  return lines.slice(0, 3);
}
